In [19]:
import numpy as np

In [20]:
data1 = [5,6,7.8,9]
type(data1)

list

In [21]:
arr1 = np.array(data1)
type(arr1)

numpy.ndarray

In [22]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
type(arr2)

numpy.ndarray

In [23]:
arr2.ndim

2

In [24]:
arr2.dtype

dtype('int64')

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
np.arange(15)  #arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [29]:
arr1.dtype

dtype('float64')

In [30]:
arr2 = np.array([1,2,3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [31]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [33]:
float_arr = arr.astype(np.float64)  #astype
float_arr.dtype

dtype('float64')

In [34]:
arry = np.array([3.7, -1.2, -2.6])

In [35]:
arry.astype(np.int32)  #if data type float==>int, decimal point will be deleted

array([ 3, -1, -2], dtype=int32)

In [36]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]]) #float

In [37]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [38]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [40]:
1/arr  #propagation

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [41]:
arr ** 0.05

array([[1.        , 1.03526492, 1.05646731],
       [1.07177346, 1.08379839, 1.09372355]])

In [42]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [44]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [45]:
arr > arr2

array([[ True, False,  True],
       [False,  True, False]])

In [46]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr[5]

5

In [48]:
arr[5:8]

array([5, 6, 7])

In [49]:
arr[5:8] = 12

In [50]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [51]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [53]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr2d[0]

array([1, 2, 3])

In [55]:
arr2d[0][2]

3

In [57]:
arr2d[0, 2]

3

In [61]:
arr3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

In [63]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [60]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
arr2d[:2, 0] #column

array([1, 4])

In [68]:
arr2d[:, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [69]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [70]:
data

array([[ 1.13101743e+00,  5.23531643e-01,  5.35900888e-02,
         1.89519630e+00],
       [ 6.47887839e-01, -7.71211102e-01,  9.62568454e-01,
        -9.70731157e-01],
       [-3.37459648e-01, -6.03772789e-02, -6.70930010e-01,
         7.65778026e-01],
       [-8.47269869e-01,  2.37692991e-01, -2.42457557e-01,
        -1.45802694e+00],
       [ 1.13407323e-03, -1.10625405e+00,  2.98186290e-01,
         1.73290144e+00],
       [ 1.58655734e+00,  1.74737965e+00, -1.41258809e-01,
        -1.48080064e-01],
       [-4.32697036e-01,  1.38302366e+00, -3.88586161e-02,
         7.87523787e-01]])

In [71]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [72]:
data[names == 'Bob']

array([[ 1.13101743,  0.52353164,  0.05359009,  1.8951963 ],
       [-0.84726987,  0.23769299, -0.24245756, -1.45802694]])

In [73]:
data[names == 'Bob', 2:]

array([[ 0.05359009,  1.8951963 ],
       [-0.24245756, -1.45802694]])

In [74]:
data[names != 'Bob']

array([[ 6.47887839e-01, -7.71211102e-01,  9.62568454e-01,
        -9.70731157e-01],
       [-3.37459648e-01, -6.03772789e-02, -6.70930010e-01,
         7.65778026e-01],
       [ 1.13407323e-03, -1.10625405e+00,  2.98186290e-01,
         1.73290144e+00],
       [ 1.58655734e+00,  1.74737965e+00, -1.41258809e-01,
        -1.48080064e-01],
       [-4.32697036e-01,  1.38302366e+00, -3.88586161e-02,
         7.87523787e-01]])

In [76]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [77]:
data[mask]

array([[ 1.13101743e+00,  5.23531643e-01,  5.35900888e-02,
         1.89519630e+00],
       [-3.37459648e-01, -6.03772789e-02, -6.70930010e-01,
         7.65778026e-01],
       [-8.47269869e-01,  2.37692991e-01, -2.42457557e-01,
        -1.45802694e+00],
       [ 1.13407323e-03, -1.10625405e+00,  2.98186290e-01,
         1.73290144e+00]])

In [79]:
arr = np.arange(15).reshape(3, 5)

In [80]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [81]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [82]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [83]:
arr = np.arange(10)

In [84]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [85]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [86]:
x = np.random.randn(8)
x

array([-0.40567729,  0.06140776,  0.19467767, -0.59094716, -0.10734905,
       -0.28582743,  1.6136697 ,  0.02932263])

In [87]:
y = np.random.randn(8)
y

array([ 1.16495903, -1.35298246, -0.43343937,  0.80626097, -0.64779753,
        0.53604425, -0.1213874 ,  0.95624996])

In [88]:
np.maximum(x, y)

array([ 1.16495903,  0.06140776,  0.19467767,  0.80626097, -0.10734905,
        0.53604425,  1.6136697 ,  0.95624996])

In [91]:
arr = np.random.rand(7) * 5
arr

array([3.38038684, 4.73518039, 4.59765797, 0.81011644, 1.98435136,
       0.86403204, 4.71462506])

In [93]:
remainder, whole_par = np.modf(arr) #modf function

In [94]:
remainder

array([0.38038684, 0.73518039, 0.59765797, 0.81011644, 0.98435136,
       0.86403204, 0.71462506])

In [95]:
whole_par

array([3., 4., 4., 0., 1., 0., 4.])

In [97]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [98]:
cond = np.array([True, False, True, True, False])

In [99]:
result = np.where(cond, xarr, yarr) #where function ==> position based
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [100]:
arr = np.random.randn(4, 4)
arr

array([[ 0.21193189, -1.06791621, -0.90677831, -1.20192596],
       [-1.81664975, -0.5890853 , -1.1980892 ,  1.49696077],
       [-0.44361586, -0.51109104,  2.08298128,  0.99737897],
       [ 0.41424523,  0.48571321, -1.46900436,  0.08500324]])

In [101]:
arr > 0

array([[ True, False, False, False],
       [False, False, False,  True],
       [False, False,  True,  True],
       [ True,  True, False,  True]])

In [102]:
np.where(arr > 0, 2, -2)

array([[ 2, -2, -2, -2],
       [-2, -2, -2,  2],
       [-2, -2,  2,  2],
       [ 2,  2, -2,  2]])

In [103]:
np.where(arr > 0, 2, arr)

array([[ 2.        , -1.06791621, -0.90677831, -1.20192596],
       [-1.81664975, -0.5890853 , -1.1980892 ,  2.        ],
       [-0.44361586, -0.51109104,  2.        ,  2.        ],
       [ 2.        ,  2.        , -1.46900436,  2.        ]])

In [104]:
arr = np.random.rand(5, 4)
arr

array([[0.71469005, 0.62993844, 0.22801782, 0.23215796],
       [0.69039044, 0.60316075, 0.41832114, 0.49052889],
       [0.31246932, 0.34234417, 0.66852151, 0.20701236],
       [0.85039373, 0.15650458, 0.4565844 , 0.22210587],
       [0.56171993, 0.91817351, 0.57720374, 0.77662711]])

In [105]:
arr.mean()

0.5028432856979859

In [106]:
np.mean(arr)

0.5028432856979859

In [107]:
arr.sum()

10.056865713959716

In [110]:
arr.sum(axis = 0) #sum of column, 0 means row, sum across row

array([3.12966347, 2.65012146, 2.3486486 , 1.92843218])

In [111]:
arr.sum(axis=1) #sum of row, 1 means column, sum across column

array([1.80480428, 2.20240122, 1.53034736, 1.68558858, 2.83372428])

In [112]:
arr = np.random.randn(100)
arr

array([-0.98299464,  0.69101189,  0.0786239 , -0.40188345, -0.31745827,
        0.68236864, -0.43840236, -1.12765294, -0.13401638,  0.00331247,
       -2.32448581, -0.59566491,  2.69526222,  0.47783874,  0.10926887,
        0.11709329,  0.30614545,  0.03316777,  0.31376834, -1.43440297,
        0.84548014, -1.89539213, -0.76327455,  2.02040171,  0.23597042,
        0.85464301, -0.98752847,  1.08722972,  1.0282773 ,  2.8449405 ,
        1.39159805, -0.17714624, -1.22124525, -1.47524805, -1.11856116,
        0.07767615,  0.04147925, -1.5862492 ,  0.95842172, -1.66988805,
       -0.28001543, -1.43969198,  1.17690627,  0.40582313, -0.05935433,
       -0.8210697 , -0.63511509,  0.86206167, -1.04672739, -1.29074012,
        1.64956217,  0.15356499, -0.0444016 ,  0.13851955,  0.51197019,
        0.24641416,  1.23549235,  0.11798318,  2.17132957, -0.3027708 ,
       -1.08235551, -0.89663609, -0.5561352 , -0.66099912,  0.09621962,
       -0.4535829 , -0.06363165, -0.08379918, -0.59762471,  1.16

In [113]:
(arr>0).sum() #count number of positive values

45

In [114]:
bools = np.array([False, False, True, False])
bools.any() #any more than one True

True

In [115]:
bools.all() #all true?

False

In [116]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [118]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [120]:
y.dtype

dtype('float64')

In [121]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])